quarkus.funqy.export=enviarEmail
resend.api.key=${RESEND_API_KEY}

quarkus.index-dependency.common.group-id=br.com.fiap.tc4
quarkus.index-dependency.common.artifact-id=common

quarkus.datasource.db-kind = mysql
quarkus.datasource.username = ${DB_USER}
quarkus.datasource.password = ${DB_PASSWORD}
quarkus.datasource.jdbc.url = ${DB_URL}

quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}